# yamllint disable rule:line-length

name: Code Style

on:
  pull_request:
  push:
    branches:
      - trunk

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['7.4']

    name: PHPCS

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php-version }}
          tools: composer:v2

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('composer.*') }}
          restore-keys: |
            composer-${{ runner.os }}-${{ matrix.php-version }}-
            composer-${{ runner.os }}-
            composer-

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-interaction --no-progress

      - name: Check code style
        run: |
          composer php:lint
